language: python
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: WqqXDbH3u31fWin7Ty7jMgTsDMcLp5iYcC6y3IAJhmGfCY/tOEbo7JH22jR9nwR0UUtq+ZGCNmXczSDSJH2U3ALqMWluKpjnmW8wknnJqE0Deryh+yoze6jaqkD/cg8q372xPKBcuY1YnUDRZn1c+huTHo6naUICD6eJyzCKL4Q+sshFvmHSSEUUrQWQKvOI+FWhAE7lqWLih68Njl7UmOlJ6h6JKGKIxXfkfjsWe3w1iazktt5dZIFoABMbaTsTce6K9B6sxIrchxiOVa4P+Z/kONFcqvMO1ObTJG5xe4OPfDu2A1ntQCw2vuLLP2liuxz/Lx8E+EkQeyXt1OwqbQy1ft3JLoC6n6YPYZyd5dBWHnDaszkZGVBvDGi7NaW1j9H23xqbAh/VMbRGwRcCljGsnGjWsVY+X/9zWizq3pd2aGgmlceGIV8jLkKC/W6InGwEKIJkofdyi7d+wljKQnYTuskR8o/ncOLu3druGo8OZ6yV44cvkE5fEQuRuuXlMisD0RFASGJ+cwtc56zk0CbyRPvL75zMnKTwTiuAZfMlyUH0R31gygyA4VitCS45OxdWwlcaHRXeV2Je1FKIeoPgxWFc1oomtZYHZlno6ybaR+Sc5CHB5GGxRo0llJnkZiGYjYp6odeL+LVhVDpk82ZdBXmADpsCGCMoOvOxdNI=
  on:
    branch: master
    tags: true